-- Real card images from the Bulbagarden Archives MEP gallery.
insert into public.master_set_catalog (set_id, card_id, variant, card_number, card_name, image_url, rarity, sort_order) values
('mep','mep-001','holo','001','Meganium','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MeganiumMEPPromo1.jpg','Promo',0),
('mep','mep-002','holo','002','Inteleon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/InteleonMEPPromo2.jpg','Promo',10),
('mep','mep-003','holo','003','Alakazam','https://archives.bulbagarden.net/wiki/Special:Redirect/file/AlakazamMEPPromo3.jpg','Promo',20),
('mep','mep-004','holo','004','Lunatone','https://archives.bulbagarden.net/wiki/Special:Redirect/file/LunatoneMEPPromo4.jpg','Promo',30),
('mep','mep-005','holo','005','Drifloon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DrifloonMEPPromo5.jpg','Promo',40),
('mep','mep-006','holo','006','Drifblim','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DrifblimMEPPromo6.jpg','Promo',50),
('mep','mep-007','holo','007','Psyduck','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PsyduckMEPPromo7.jpg','Promo',60),
('mep','mep-008','holo','008','Golduck','https://archives.bulbagarden.net/wiki/Special:Redirect/file/GolduckMEPPromo8.jpg','Promo',70),
('mep','mep-009','holo','009','Alakazam','https://archives.bulbagarden.net/wiki/Special:Redirect/file/AlakazamMEPPromo9.jpg','Promo',80),
('mep','mep-010','holo','010','Riolu','https://archives.bulbagarden.net/wiki/Special:Redirect/file/RioluMEPPromo10.jpg','Promo',90),
('mep','mep-011','holo','011','Mega Latias ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaLatiasexMEPPromo11.jpg','Promo',100),
('mep','mep-012','holo','012','Mega Lucario ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaLucarioexMEPPromo12.jpg','Promo',110),
('mep','mep-013','holo','013','Mega Venusaur ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaVenusaurexMEPPromo13.jpg','Promo',120),
('mep','mep-014','holo','014','Ceruledge','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CeruledgeMEPPromo14.jpg','Promo',130),
('mep','mep-015','holo','015','Zacian','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ZacianMEPPromo15.jpg','Promo',140),
('mep','mep-016','holo','016','Flygon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/FlygonMEPPromo16.jpg','Promo',150),
('mep','mep-017','holo','017','Toxtricity','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ToxtricityMEPPromo17.jpg','Promo',160),
('mep','mep-018','holo','018','Cottonee','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CottoneeMEPPromo18.jpg','Promo',170),
('mep','mep-019','holo','019','Whimsicott','https://archives.bulbagarden.net/wiki/Special:Redirect/file/WhimsicottMEPPromo19.jpg','Promo',180),
('mep','mep-020','holo','020','Sneasel','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SneaselMEPPromo20.jpg','Promo',190),
('mep','mep-021','holo','021','Weavile','https://archives.bulbagarden.net/wiki/Special:Redirect/file/WeavileMEPPromo21.jpg','Promo',200),
('mep','mep-022','holo','022','Charcadet','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CharcadetMEPPromo22.jpg','Promo',210),
('mep','mep-023','holo','023','Mega Charizard X ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaCharizardXexMEPPromo23.jpg','Promo',220),
('mep','mep-024','holo','024','Oricorio ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/OricorioexMEPPromo24.jpg','Promo',230),
('mep','mep-025','holo','025','Mega Kangaskhan ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaKangaskhanexMEPPromo25.jpg','Promo',240),
('mep','mep-026','holo','026','Meloetta','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MeloettaMEPPromo26.jpg','Promo',250),
('mep','mep-027','holo','027','Haunter','https://archives.bulbagarden.net/wiki/Special:Redirect/file/HaunterMEPPromo27.jpg','Promo',260),
('mep','mep-028','holo','028','Promo 028','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CelebratoryFanfareMEPPromo28.jpg','Promo',270),
('mep','mep-029','holo','029','Mega Charizard X ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaCharizardXexMEPPromo29.jpg','Promo',280),
('mep','mep-030','holo','030','Mega Charizard Y ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaCharizardYexMEPPromo30.jpg','Promo',290),
('mep','mep-031','holo','031','Zekrom do N','https://archives.bulbagarden.net/wiki/Special:Redirect/file/NZekromMEPPromo31.jpg','Promo',300),
('mep','mep-032','holo','032','Mega Gardevoir ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaGardevoirexMEPPromo32.jpg','Promo',310),
('mep','mep-033','holo','033','Mega Lucario ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaLucarioexMEPPromo33.jpg','Promo',320),
('mep','mep-034','holo','034','Mega Meganium ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaMeganiumexMEPPromo34.jpg','Promo',330),
('mep','mep-035','holo','035','Mega Emboar ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaEmboarexMEPPromo35.jpg','Promo',340),
('mep','mep-036','holo','036','Mega Feraligatr ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaFeraligatrexMEPPromo36.jpg','Promo',350),
('mep','mep-037','holo','037','Bulbasaur','https://archives.bulbagarden.net/wiki/Special:Redirect/file/BulbasaurMEPPromo37.jpg','Promo',360),
('mep','mep-038','holo','038','Charmander','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CharmanderMEPPromo38.jpg','Promo',370),
('mep','mep-039','holo','039','Squirtle','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SquirtleMEPPromo39.jpg','Promo',380),
('mep','mep-040','holo','040','Turtwig','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TurtwigMEPPromo40.jpg','Promo',390),
('mep','mep-041','holo','041','Chimchar','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ChimcharMEPPromo41.jpg','Promo',400),
('mep','mep-042','holo','042','Piplup','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PiplupMEPPromo42.jpg','Promo',410),
('mep','mep-043','holo','043','Rowlet','https://archives.bulbagarden.net/wiki/Special:Redirect/file/RowletMEPPromo43.jpg','Promo',420),
('mep','mep-044','holo','044','Litten','https://archives.bulbagarden.net/wiki/Special:Redirect/file/LittenMEPPromo44.jpg','Promo',430),
('mep','mep-045','holo','045','Popplio','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PopplioMEPPromo45.jpg','Promo',440),
('mep','mep-046','holo','046','Chikorita','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ChikoritaMEPPromo46.jpg','Promo',450),
('mep','mep-047','holo','047','Cyndaquil','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CyndaquilMEPPromo47.jpg','Promo',460),
('mep','mep-048','holo','048','Totodile','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TotodileMEPPromo48.jpg','Promo',470),
('mep','mep-049','holo','049','Snivy','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SnivyMEPPromo49.jpg','Promo',480),
('mep','mep-050','holo','050','Tepig','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TepigMEPPromo50.jpg','Promo',490),
('mep','mep-051','holo','051','Oshawott','https://archives.bulbagarden.net/wiki/Special:Redirect/file/OshawottMEPPromo51.jpg','Promo',500),
('mep','mep-052','holo','052','Grookey','https://archives.bulbagarden.net/wiki/Special:Redirect/file/GrookeyMEPPromo52.jpg','Promo',510),
('mep','mep-053','holo','053','Scorbunny','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ScorbunnyMEPPromo53.jpg','Promo',520),
('mep','mep-054','holo','054','Sobble','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SobbleMEPPromo54.jpg','Promo',530),
('mep','mep-055','holo','055','Treecko','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TreeckoMEPPromo55.jpg','Promo',540),
('mep','mep-056','holo','056','Torchic','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TorchicMEPPromo56.jpg','Promo',550),
('mep','mep-057','holo','057','Mudkip','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MudkipMEPPromo57.jpg','Promo',560),
('mep','mep-058','holo','058','Chespin','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ChespinMEPPromo58.jpg','Promo',570),
('mep','mep-059','holo','059','Fennekin','https://archives.bulbagarden.net/wiki/Special:Redirect/file/FennekinMEPPromo59.jpg','Promo',580),
('mep','mep-060','holo','060','Froakie','https://archives.bulbagarden.net/wiki/Special:Redirect/file/FroakieMEPPromo60.jpg','Promo',590),
('mep','mep-061','holo','061','Sprigatito','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SprigatitoMEPPromo61.jpg','Promo',600),
('mep','mep-062','holo','062','Fuecoco','https://archives.bulbagarden.net/wiki/Special:Redirect/file/FuecocoMEPPromo62.jpg','Promo',610),
('mep','mep-063','holo','063','Quaxly','https://archives.bulbagarden.net/wiki/Special:Redirect/file/QuaxlyMEPPromo63.jpg','Promo',620),
('mep','mep-064','holo','064','Serperior','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SerperiorMEPPromo64.jpg','Promo',630),
('mep','mep-065','holo','065','Barbaracle','https://archives.bulbagarden.net/wiki/Special:Redirect/file/BarbaracleMEPPromo65.jpg','Promo',640),
('mep','mep-066','holo','066','Tyrantrum','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TyrantrumMEPPromo66.jpg','Promo',650),
('mep','mep-067','holo','067','Doublade','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DoubladeMEPPromo67.jpg','Promo',660),
('mep','mep-068','holo','068','Makuhita','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MakuhitaMEPPromo68.jpg','Promo',670),
('mep','mep-069','holo','069','Chikorita','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ChikoritaMEPPromo69.jpg','Promo',680),
('mep','mep-070','holo','070','Tyrunt','https://archives.bulbagarden.net/wiki/Special:Redirect/file/TyruntMEPPromo70.jpg','Promo',690),
('mep','mep-071','holo','071','Mega Zygarde ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaZygardeexMEPPromo71.jpg','Promo',700),
('mep','mep-072','holo','072','Mega Clefable ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaClefableexMEPPromo72.jpg','Promo',710),
('mep','mep-073','holo','073','Mega Gengar ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaGengarexMEPPromo73.jpg','Promo',720),
('mep','mep-074','holo','074','Delphox','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DelphoxMEPPromo74.jpg','Promo',730),
('mep','mep-075','holo','075','Ampharos','https://archives.bulbagarden.net/wiki/Special:Redirect/file/AmpharosMEPPromo75.jpg','Promo',740),
('mep','mep-076','holo','076','Crobat','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CrobatMEPPromo76.jpg','Promo',750),
('mep','mep-077','holo','077','Goodra','https://archives.bulbagarden.net/wiki/Special:Redirect/file/GoodraMEPPromo77.jpg','Promo',760),
('mep','mep-078','holo','078','Toxel','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ToxelMEPPromo78.jpg','Promo',770),
('mep','mep-079','holo','079','Charmeleon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/CharmeleonMEPPromo79.jpg','Promo',780),
('mep','mep-080','holo','080','Fennekin','https://archives.bulbagarden.net/wiki/Special:Redirect/file/FennekinMEPPromo80.jpg','Promo',790),
('mep','mep-081','holo','081','Mega Greninja ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaGreninjaexMEPPromo81.jpg','Promo',800),
('mep','mep-082','holo','082','Miraidon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MiraidonMEPPromo82.jpg','Promo',810),
('mep','mep-083','holo','083','Slowbro','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SlowbroMEPPromo83.jpg','Promo',820),
('mep','mep-084','holo','084','Dhelmise','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DhelmiseMEPPromo84.jpg','Promo',830),
('mep','mep-085','holo','085','Bastiodon','https://archives.bulbagarden.net/wiki/Special:Redirect/file/BastiodonMEPPromo85.jpg','Promo',840),
('mep','mep-086','holo','086','Slowpoke','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SlowpokeMEPPromo86.jpg','Promo',850),
('mep','mep-087','holo','087','Binacle','https://archives.bulbagarden.net/wiki/Special:Redirect/file/BinacleMEPPromo87.jpg','Promo',860),
('mep','mep-088','holo','088','Zarude','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ZarudeMEPPromo88.jpg','Promo',870),
('mep','mep-089','holo','089','Mega Zeraora ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaZeraoraexMEPPromo89.jpg','Promo',880),
('mep','mep-090','holo','090','Mega Darkrai ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaDarkraiexMEPPromo90.jpg','Promo',890),
('mep','mep-091','holo','091','Mega Dragonite ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MegaDragoniteexMEPPromo91.jpg','Promo',900),
('mep','mep-092','holo','092','Paradise Resort','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ParadiseResortMEPPromo92.jpg','Promo',910),
('mep','mep-093','holo','093','Pikachu','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PikachuMEPPromo93.jpg','Promo',920),
('mep','mep-094','holo','094','Alolan Exeggutor','https://archives.bulbagarden.net/wiki/Special:Redirect/file/AlolanExeggutorMEPPromo94.jpg','Promo',930),
('mep','mep-095','holo','095','Lucario','https://archives.bulbagarden.net/wiki/Special:Redirect/file/LucarioMEPPromo95.jpg','Promo',940),
('mep','mep-096','holo','096','Moltres','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MoltresMEPPromo96.jpg','Promo',950),
('mep','mep-097','holo','097','Articuno','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ArticunoMEPPromo97.jpg','Promo',960),
('mep','mep-098','holo','098','Zapdos','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ZapdosMEPPromo98.jpg','Promo',970),
('mep','mep-099','holo','099','Greninja ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/GreninjaexMEPPromo99.jpg','Promo',980),
('mep','mep-100','holo','100','Sylveon ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/SylveonexMEPPromo100.jpg','Promo',990),
('mep','mep-101','holo','101','Nidorina','https://archives.bulbagarden.net/wiki/Special:Redirect/file/NidorinaMEPPromo101.jpg','Promo',1000),
('mep','mep-102','holo','102','Victini','https://archives.bulbagarden.net/wiki/Special:Redirect/file/VictiniMEPPromo102.jpg','Promo',1010),
('mep','mep-103','holo','103','Zeraora','https://archives.bulbagarden.net/wiki/Special:Redirect/file/ZeraoraMEPPromo103.jpg','Promo',1020),
('mep','mep-104','holo','104','Mewtwo','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MewtwoMEPPromo104.jpg','Promo',1030),
('mep','mep-105','holo','105','Mew','https://archives.bulbagarden.net/wiki/Special:Redirect/file/MewMEPPromo105.jpg','Promo',1040),
('mep','mep-106','holo','106','Ditto','https://archives.bulbagarden.net/wiki/Special:Redirect/file/DittoMEPPromo106.jpg','Promo',1050),
('mep','mep-107','holo','107','Pikachu ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PikachuexMEPPromo107.jpg','Promo',1060),
('mep','mep-108','holo','108','Espeon ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/EspeonexMEPPromo108.jpg','Promo',1070),
('mep','mep-109','holo','109','Pikachu ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/PikachuexMEPPromo109.jpg','Promo',1080),
('mep','mep-110','holo','110','Umbreon ex','https://archives.bulbagarden.net/wiki/Special:Redirect/file/UmbreonexMEPPromo110.jpg','Promo',1090)
on conflict (set_id, card_id, variant) do update set card_number=excluded.card_number, card_name=excluded.card_name, image_url=excluded.image_url, rarity=excluded.rarity, sort_order=excluded.sort_order;

